version: '3.8'

services:

  etl_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: properly_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: >
            python ./etl_socrata_api_job.py
    links:
      - mysql_db
    depends_on:
      mysql_db:
        condition: service_healthy
    restart:
      on-failure
    networks:
      - app_network

  etl_csv:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: properly_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: >
      python ./etl_csv_job.py
    links:
      - mysql_db
    depends_on:
      mysql_db:
        condition: service_healthy
    restart:
      on-failure
    networks:
      - app_network


  mysql_db:
    image: mysql:8.0.26
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: properly_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 50
    networks:
      - app_network

networks:
  app_network:
    driver: bridge